// Generated by gencpp from file ros_assignments/InputService.msg
// DO NOT EDIT!


#ifndef ROS_ASSIGNMENTS_MESSAGE_INPUTSERVICE_H
#define ROS_ASSIGNMENTS_MESSAGE_INPUTSERVICE_H

#include <ros/service_traits.h>


#include <ros_assignments/InputServiceRequest.h>
#include <ros_assignments/InputServiceResponse.h>


namespace ros_assignments
{

struct InputService
{

typedef InputServiceRequest Request;
typedef InputServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InputService
} // namespace ros_assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_assignments::InputService > {
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::ros_assignments::InputService&) { return value(); }
};

template<>
struct DataType< ::ros_assignments::InputService > {
  static const char* value()
  {
    return "ros_assignments/InputService";
  }

  static const char* value(const ::ros_assignments::InputService&) { return value(); }
};


// service_traits::MD5Sum< ::ros_assignments::InputServiceRequest> should match 
// service_traits::MD5Sum< ::ros_assignments::InputService > 
template<>
struct MD5Sum< ::ros_assignments::InputServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_assignments::InputService >::value();
  }
  static const char* value(const ::ros_assignments::InputServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_assignments::InputServiceRequest> should match 
// service_traits::DataType< ::ros_assignments::InputService > 
template<>
struct DataType< ::ros_assignments::InputServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_assignments::InputService >::value();
  }
  static const char* value(const ::ros_assignments::InputServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_assignments::InputServiceResponse> should match 
// service_traits::MD5Sum< ::ros_assignments::InputService > 
template<>
struct MD5Sum< ::ros_assignments::InputServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_assignments::InputService >::value();
  }
  static const char* value(const ::ros_assignments::InputServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_assignments::InputServiceResponse> should match 
// service_traits::DataType< ::ros_assignments::InputService > 
template<>
struct DataType< ::ros_assignments::InputServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_assignments::InputService >::value();
  }
  static const char* value(const ::ros_assignments::InputServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ASSIGNMENTS_MESSAGE_INPUTSERVICE_H
