// Generated by gencpp from file ros_assignments/ServiceCall.msg
// DO NOT EDIT!


#ifndef ROS_ASSIGNMENTS_MESSAGE_SERVICECALL_H
#define ROS_ASSIGNMENTS_MESSAGE_SERVICECALL_H

#include <ros/service_traits.h>


#include <ros_assignments/ServiceCallRequest.h>
#include <ros_assignments/ServiceCallResponse.h>


namespace ros_assignments
{

struct ServiceCall
{

typedef ServiceCallRequest Request;
typedef ServiceCallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceCall
} // namespace ros_assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_assignments::ServiceCall > {
  static const char* value()
  {
    return "7beedea2ad148ed58820807ce9337bb3";
  }

  static const char* value(const ::ros_assignments::ServiceCall&) { return value(); }
};

template<>
struct DataType< ::ros_assignments::ServiceCall > {
  static const char* value()
  {
    return "ros_assignments/ServiceCall";
  }

  static const char* value(const ::ros_assignments::ServiceCall&) { return value(); }
};


// service_traits::MD5Sum< ::ros_assignments::ServiceCallRequest> should match 
// service_traits::MD5Sum< ::ros_assignments::ServiceCall > 
template<>
struct MD5Sum< ::ros_assignments::ServiceCallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_assignments::ServiceCall >::value();
  }
  static const char* value(const ::ros_assignments::ServiceCallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_assignments::ServiceCallRequest> should match 
// service_traits::DataType< ::ros_assignments::ServiceCall > 
template<>
struct DataType< ::ros_assignments::ServiceCallRequest>
{
  static const char* value()
  {
    return DataType< ::ros_assignments::ServiceCall >::value();
  }
  static const char* value(const ::ros_assignments::ServiceCallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_assignments::ServiceCallResponse> should match 
// service_traits::MD5Sum< ::ros_assignments::ServiceCall > 
template<>
struct MD5Sum< ::ros_assignments::ServiceCallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_assignments::ServiceCall >::value();
  }
  static const char* value(const ::ros_assignments::ServiceCallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_assignments::ServiceCallResponse> should match 
// service_traits::DataType< ::ros_assignments::ServiceCall > 
template<>
struct DataType< ::ros_assignments::ServiceCallResponse>
{
  static const char* value()
  {
    return DataType< ::ros_assignments::ServiceCall >::value();
  }
  static const char* value(const ::ros_assignments::ServiceCallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ASSIGNMENTS_MESSAGE_SERVICECALL_H
