// Generated by gencpp from file ros_assignments/StateService.msg
// DO NOT EDIT!


#ifndef ROS_ASSIGNMENTS_MESSAGE_STATESERVICE_H
#define ROS_ASSIGNMENTS_MESSAGE_STATESERVICE_H

#include <ros/service_traits.h>


#include <ros_assignments/StateServiceRequest.h>
#include <ros_assignments/StateServiceResponse.h>


namespace ros_assignments
{

struct StateService
{

typedef StateServiceRequest Request;
typedef StateServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StateService
} // namespace ros_assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_assignments::StateService > {
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::ros_assignments::StateService&) { return value(); }
};

template<>
struct DataType< ::ros_assignments::StateService > {
  static const char* value()
  {
    return "ros_assignments/StateService";
  }

  static const char* value(const ::ros_assignments::StateService&) { return value(); }
};


// service_traits::MD5Sum< ::ros_assignments::StateServiceRequest> should match 
// service_traits::MD5Sum< ::ros_assignments::StateService > 
template<>
struct MD5Sum< ::ros_assignments::StateServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_assignments::StateService >::value();
  }
  static const char* value(const ::ros_assignments::StateServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_assignments::StateServiceRequest> should match 
// service_traits::DataType< ::ros_assignments::StateService > 
template<>
struct DataType< ::ros_assignments::StateServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ros_assignments::StateService >::value();
  }
  static const char* value(const ::ros_assignments::StateServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_assignments::StateServiceResponse> should match 
// service_traits::MD5Sum< ::ros_assignments::StateService > 
template<>
struct MD5Sum< ::ros_assignments::StateServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_assignments::StateService >::value();
  }
  static const char* value(const ::ros_assignments::StateServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_assignments::StateServiceResponse> should match 
// service_traits::DataType< ::ros_assignments::StateService > 
template<>
struct DataType< ::ros_assignments::StateServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ros_assignments::StateService >::value();
  }
  static const char* value(const ::ros_assignments::StateServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ASSIGNMENTS_MESSAGE_STATESERVICE_H
