(cl:defpackage ros_assignments-srv
  (:use )
  (:export
   "SERVICECALL"
   "<SERVICECALL-REQUEST>"
   "SERVICECALL-REQUEST"
   "<SERVICECALL-RESPONSE>"
   "SERVICECALL-RESPONSE"
   "INPUTSERVICE"
   "<INPUTSERVICE-REQUEST>"
   "INPUTSERVICE-REQUEST"
   "<INPUTSERVICE-RESPONSE>"
   "INPUTSERVICE-RESPONSE"
   "STATESERVICE"
   "<STATESERVICE-REQUEST>"
   "STATESERVICE-REQUEST"
   "<STATESERVICE-RESPONSE>"
   "STATESERVICE-RESPONSE"
  ))

